sudo: require
language: generic 
services:
  - docker

before install:
  - docker build -t ammar1ammar1/react-test -f ./client/Dcokerfile.dev ./client

script:
   - docker run -e CI=true ammar1ammar1/react-test npm test

after_success:
  - docker build -t ammar1ammar1/multi-client ./client 
  - docker build -t ammar1ammar1/multi-nginx ./nginx
  - docker build -t ammar1ammar1/multi-server ./server
  - docker build -t ammar1ammar1/multi-worker ./worker
  # login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push to docker hub
  - docker push ammar1ammar1/mutli-client
  - docker push ammar1ammar1/multi-nginx
  - docker push ammar1ammar1/multi-server
  - docker push ammar1ammar1/multi-worker